package dk.sdu.mmmi.pms.infrastructure.account.persistence;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AccountJpaEntityTest {
    @Test
    void defaultConstructor_ExistsForJpa() {
        assertDoesNotThrow(() -> {
            AccountJpaEntity entity = new AccountJpaEntity();
            assertNull(entity.getId());  // ID typically generated by JPA
        });
    }
}